#ifndef COMMON_WATER_GL460_FS
#define COMMON_WATER_GL460_FS

#include "common_gl460.fs"

struct DrawWater_params_t
{
    vec2 vBumpTexCoord;
#if MULTITEXTURE
    vec4 vExtraBumpTexCoord;
#endif
    vec4 vReflectXY_vRefractYX;
    float w;
    vec4 vReflectRefractScale;
    float fReflectOverbright;
    vec4 vReflectTint;
    vec4 vRefractTint;
    vec3 vTangentEyeVect;
    vec4 waterFogColor;
#if BASETEXTURE
    vec4 lightmapTexCoord1And2;
    vec4 lightmapTexCoord3;
#endif
    vec4 vProjPos;
    vec4 pixelFogParams;
    float fWaterFogStart;
    float fWaterFogEndMinusStart;
};

void DrawWater(in DrawWater_params_t i,
#if BASETEXTURE
               in sampler2D BaseTextureSampler,
               in sampler2D LightmapSampler,
#endif
               in sampler2D NormalSampler,
               in sampler2D RefractSampler,
               in sampler2D ReflectSampler,
               out vec4 result, out float fogFactor)
{
    bool bReflect = REFLECT != 0;
    bool bRefract = REFRACT != 0;

#if MULTITEXTURE
    vec4 vNormal  = texture(NormalSampler, i.vBumpTexCoord);
    vec4 vNormal1 = texture(NormalSampler, i.vExtraBumpTexCoord.xy);
    vec4 vNormal2 = texture(NormalSampler, i.vExtraBumpTexCoord.zw);
    vNormal = 0.33 * (vNormal + vNormal1 + vNormal2);

#if ( NORMAL_DECODE_MODE == NORM_DECODE_ATI2N )
    vNormal.xy = vNormal.xy * 2.0 - 1.0;
    vNormal.z = sqrt(1.0 - dot(vNormal.xy, vNormal.xy));
    vNormal.a = 1.0;
#else
    vNormal.xyz = 2.0 * vNormal.xyz - 1.0;
#endif

#else
    vec4 vNormal = DecompressNormal(NormalSampler, i.vBumpTexCoord, NORMAL_DECODE_MODE);
#endif

    // Perform division by W only once
    float ooW = 1.0 / i.w;

    vec2 unwarpedRefractTexCoord = i.vReflectXY_vRefractYX.wz * ooW;

#if ABOVEWATER
    float waterFogDepthValue = texture(RefractSampler, unwarpedRefractTexCoord).a;
#else
    // We don't actually have valid depth values in alpha when we are underwater looking out, so
    // just set to farthest value.
    float waterFogDepthValue = 1.0;
#endif
    vec4 reflectRefractScale = i.vReflectRefractScale;
#if !BASETEXTURE
#if ( BLURRY_REFRACT == 0 )
    reflectRefractScale *= waterFogDepthValue;
#endif
#endif

    // Compute coordinates for sampling Reflection
    vec2 vReflectTexCoord;
    vec2 vRefractTexCoord;

    // vectorize the dependent UV calculations (reflect = .xy, refract = .wz)
    vec4 vN;
    vN.xy = vNormal.xy;
    vN.w = vNormal.x;
    vN.z = vNormal.y;
    vec4 vDependentTexCoords = vN * vNormal.a * reflectRefractScale;

    vDependentTexCoords += (i.vReflectXY_vRefractYX * ooW);
    vReflectTexCoord = vDependentTexCoords.xy;
    vRefractTexCoord = vDependentTexCoords.wz;

    vec4 vReflectColor = texture(ReflectSampler, vReflectTexCoord);
#if BLURRY_REFRACT
    // Sample reflection and refraction
    vec2 ddx1 = vec2(0.005, 0);
    vec2 ddy1 = vec2(0, 0.005);
    vec4 vRefractColor = vec4(0, 0, 0, 0);

    // NOTE: Generated by genwaterloop.pl in the stdshaders directory.
    // Need to unroll for 360 to avoid shader compilation problems.
    // Modified genwaterloop.pl and regenerate if you need different params
    vRefractColor += texture(RefractSampler, vRefractTexCoord + -2.0 * ddx1 + -2.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + -2.0 * ddx1 + -1.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + -2.0 * ddx1 + 0.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + -2.0 * ddx1 + 1.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + -2.0 * ddx1 + 2.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + -1.0 * ddx1 + -2.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + -1.0 * ddx1 + -1.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + -1.0 * ddx1 + 0.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + -1.0 * ddx1 + 1.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + -1.0 * ddx1 + 2.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + 0.0 * ddx1 + -2.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + 0.0 * ddx1 + -1.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + 0.0 * ddx1 + 0.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + 0.0 * ddx1 + 1.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + 0.0 * ddx1 + 2.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + 1.0 * ddx1 + -2.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + 1.0 * ddx1 + -1.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + 1.0 * ddx1 + 0.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + 1.0 * ddx1 + 1.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + 1.0 * ddx1 + 2.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + 2.0 * ddx1 + -2.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + 2.0 * ddx1 + -1.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + 2.0 * ddx1 + 0.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + 2.0 * ddx1 + 1.0 * ddy1);
    vRefractColor += texture(RefractSampler, vRefractTexCoord + 2.0 * ddx1 + 2.0 * ddy1);
    float sumweights = 25.0;
    // NOTE: end of generated code.

    vRefractColor *= (1.0 / sumweights);
    vReflectColor *= i.fReflectOverbright;
    vReflectColor *= i.vReflectTint;
    vRefractColor *= i.vRefractTint;
#	if ABOVEWATER
        // Don't mess with this in the underwater case since we don't really have
        // depth values there.
        // get the blurred depth value to be used for fog.
    waterFogDepthValue = vRefractColor.a;
#	endif
#else
    vReflectColor *= i.vReflectTint;
    vec4 vRefractColor = texture(RefractSampler, vRefractTexCoord);
    // get the depth value from the refracted sample to be used for fog.
#	if ABOVEWATER
    // Don't mess with this in the underwater case since we don't really have
    // depth values there.
    waterFogDepthValue = texture(RefractSampler, vRefractTexCoord).a;
#	endif
#endif

    vec3 vEyeVect;
    vEyeVect = normalize(i.vTangentEyeVect);

    // Fresnel term
    float fNdotV = clamp(dot(vEyeVect, vNormal.xyz), 0.0, 1.0);
    float fFresnel = pow(1.0 - fNdotV, 5.0);

#if !BASETEXTURE
    // fFresnel == 1.0f means full reflection
    fFresnel *= clamp((waterFogDepthValue - 0.05) * 20.0, 0.0, 1.0);
#endif


    // blend between refraction and fog color.
#if ABOVEWATER
    vRefractColor = mix(vRefractColor, i.waterFogColor * LINEAR_LIGHT_SCALE, clamp(waterFogDepthValue - 0.05, 0.0, 1.0));
#else
    float waterFogFactor = clamp((i.vProjPos.z - i.fWaterFogStart) / i.fWaterFogEndMinusStart, 0.0, 1.0);
    vRefractColor = mix(vRefractColor, i.waterFogColor * LINEAR_LIGHT_SCALE, waterFogFactor);
#endif

#if BASETEXTURE
    vec4 baseSample = texture(BaseTextureSampler, i.vBumpTexCoord.xy);
    vec2 bumpCoord1;
    vec2 bumpCoord2;
    vec2 bumpCoord3;
    ComputeBumpedLightmapCoordinates(i.lightmapTexCoord1And2, i.lightmapTexCoord3.xy,
        bumpCoord1, bumpCoord2, bumpCoord3);

    vec4 lightmapSample1 = texture(LightmapSampler, bumpCoord1);
    vec3 lightmapColor1 = lightmapSample1.rgb;
    vec3 lightmapColor2 = texture(LightmapSampler, bumpCoord2).rgb;
    vec3 lightmapColor3 = texture(LightmapSampler, bumpCoord3).rgb;

    vec3 dp;
    dp.x = clamp(dot(vNormal.xyz, bumpBasis[0]), 0.0, 1.0);
    dp.y = clamp(dot(vNormal.xyz, bumpBasis[1]), 0.0, 1.0);
    dp.z = clamp(dot(vNormal.xyz, bumpBasis[2]), 0.0, 1.0);
    dp *= dp;

    vec3 diffuseLighting = dp.x * lightmapColor1 +
        dp.y * lightmapColor2 +
        dp.z * lightmapColor3;
    float sum = dot(dp, vec3(1.0, 1.0, 1.0));
    diffuseLighting *= LIGHT_MAP_SCALE / sum;
    vec3 diffuseComponent = baseSample.rgb * diffuseLighting;
#endif

    if (bReflect && bRefract)
    {
        result = mix(vRefractColor, vReflectColor, fFresnel);
    }
    else if (bReflect)
    {
#if BASETEXTURE
        result = vec4(diffuseComponent, 1.0) + vReflectColor * fFresnel * baseSample.a;
#else
        result = vReflectColor;
#endif
    }
    else if (bRefract)
    {
        result = vRefractColor;
    }
    else
    {
        result = vec4(0.0, 0.0, 0.0, 0.0);
    }

#if (PIXELFOGTYPE == PIXEL_FOG_TYPE_RANGE)
    fogFactor = CalcRangeFog(i.vProjPos.z, i.pixelFogParams.x, i.pixelFogParams.z, i.pixelFogParams.w);
#else
    fogFactor = 0.0;
#endif
}

#endif // COMMON_WATER_GL460_FS
